language: android
jdk: oraclejdk8
sudo: true 
cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/
    - ${TRAVIS_BUILD_DIR}/android-sdk/extras/
env:
  global:
    - ANDROID_API_LEVEL=25
    - ANDROID_BUILD_TOOLS_VERSION=25.0.2
android:
  components:
    - tools
    - platform-tools
    
    # Build tool version for the project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    - extra-android-m2repository

    # SDK Version to compile project
    - android-$ANDROID_API_LEVEL
script:
  - ./gradlew clean build jacocoTestReport


# Send code report to codecov.io
after_success:
  - bash <(curl -s https://codecov.io/bash)
